version: '3'

services:
    php:
        build:
            context: ./docker/php
        env_file:
            - ./docker/php/.env
        # Comment out these volumes in production
        volumes:
            - ./src:/srv/src:rw
            # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
            - /srv/src/var/
            - /srv/src/var/cache/
            - /srv/src/var/logs/

    api:
        build:
            context: ./docker/nginx
            dockerfile: ./Dockerfile
        depends_on:
            - php
        ports:
            - "8080:80"
        volumes:
            - ./src/public:/srv/src/public:ro
